apiVersion: v1
kind: Service
metadata:
  name: cicd-demo
  namespace: cicd-demo
  labels:
    app: cicd-demo
spec:
  type: ClusterIP
  selector:
    app: cicd-demo
  ports:
    - name: http          # ServiceMonitor tham chieu port theo TEN nay
      port: 80
      targetPort: 8088
      protocol: TCP
